name: Wpf 构建脚本

on: 
    workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    # https://github.com/marketplace?type=actions
    # 在上面的链接搜下面的 action 最新版本
    - uses: actions/checkout@v4
    - name: Checkout to the V8.0.0 tag
      run: |
        git checkout -b wpf_net8.0 v8.0.0  # 检出指定的 tag
    - name: 安装 Nuget
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'
    - name: 执行构建脚本
      run: .\build.cmd -pack -ci -configuration Release -prepareMachine /p:Platform=x86
    - name: 执行打包上传操作
      uses: actions/upload-artifact@v4
      with:
        name: WPF-x86
        path: ./artifacts/packages/Release/NonShipping
